contact/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = patterns('',
    url(r'^form/$', ContactFormView.as_view(), name='form'),
    url(r'^thanks/$', TemplateView.as_view(
        template_name='contact/thanks.html'), name='thanks'),
)

young/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', cache_page(60 * 15)(
        TemplateView.as_view(template_name='base.html')), name='home'),
    url(r'^', include('youngsters.urls', namespace='youngsters')),
    url(r'^', include('contact.urls', namespace='contact')),
)

youngsters/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = patterns('',
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^profile/$', TemplateView.as_view(template_name='youngsters/profile_detail.html'), name='profile'),
)

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

youngsters/forms.py
from django import forms
from django.contrib.auth import authenticate


class YoungstersLoginForm(forms.Form):
    email = forms.EmailField(max_length=254)
    password = forms.CharField(widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': "Please enter a correct email and password. "
                           "Note that both fields may be case-sensitive.",
    }
    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(username=email,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                )

        return self.cleaned_data

contact/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic import FormView
from .forms import *


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'contact/form.html'

    def get_success_url(self):
        return reverse('contact:thanks')

    def form_valid(self, form):
        send_mail('New contact', form.cleaned_data['content'],
            settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL])
        return super(ContactFormView, self).form_valid(form)

youngsters/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth import login
from django.shortcuts import render
from django.views.generic import FormView
from .forms import *


class LoginFormView(FormView):
    form_class = YoungstersLoginForm
    template_name = 'youngsters/login_form.html'

    def get_success_url(self):
        return reverse('youngsters:profile')

    def form_valid(self, form):
        user = authenticate(
                username=form.cleaned_data['email'],
                password=form.cleaned_data['password'])
        login(self.request, user)
        return super(LoginFormView, self).form_valid(form)

contact/templates/contact/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default">Send</button>
    </form>
{% endblock %}

contact/templates/contact/thanks.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <p class="lead">Thanks!</p>
{% endblock %}

young/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>world!</title>
    <link rel="stylesheet" href="https://bootswatch.com/superhero/bootstrap.min.css">
    <style>
        body { padding-bottom: 70px; }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  </head>
  <body>

    <div class="container">
        <div class="page-header row">
        <div class="col-xs-6 col-md-3">
            <a class="thumbnail">
                <img src="{% static "img/small-fundraising-heart.png" %}">
                <div class="caption">
                    <h1 class="media-heading">world!</h1>
                    <p class="lead">hello {{ request.user.email }}</p>
                </div>
            </a>
        </div>
        </div>
        {% block content %}
            <a href="{% url 'youngsters:login' %}" class="btn btn-default">Login</a>
            <a href="{% url 'contact:form' %}" class="btn btn-default">Contact form</a>
        {% endblock %}
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </body>
</html>

youngsters/templates/youngsters/login_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default">Login</button>
    </form>
{% endblock %}

youngsters/templates/youngsters/profile_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <p class="lead">You are now logged-in!</p>
{% endblock %}